language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.7

script: cd mongo-kit && sbt clean test package publishLocal publishM2 && cd ../example-playframework && sbt clean test && cd ../example-scalatra && ./sbt clean test


notifications:
  email:
    recipients:
      - mide.ojikutu@gmail.com
